-- Add migration script here
CREATE TABLE IF NOT EXISTS documents(
      id TEXT PRIMARY KEY,
      document_num TEXT,
      fournisseur_id TEXT,
      client_id TEXT,
      document_date TEXT,
      depot_id TEXT,
      commentaire TEXT,
      type_doc INTEGER,
      nombre_article REAL,
      montant_ttc REAL,
      taux_remise REAL,
      montant_remise REAL,
      montant_client REAL,
      montant_net REAL,
      montant_tva REAL,
      montant_airsi REAL,
      boutique_id INTEGER,
      attente INTEGER,
      regler INTEGER, 
      doc_parent_id TEXT,
      doc_fils_id TEXT,
      user_id TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      synchronise Integer,
      FOREIGN KEY (fournisseur_id) REFERENCES fournisseurs(id) ON DELETE SET NULL,
      FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
      FOREIGN KEY (depot_id) REFERENCES depots(id) ON DELETE SET NULL,
      FOREIGN KEY (boutique_id) REFERENCES boutiques(id) ON DELETE CASCADE,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    )